#pragma once

void SafeNewPack();
void AtkSkillWindow();
void DocumentationWindow();
// We can use a short here because the index will be 0 - 750
void HexEditorWindow(short Idx);
void SkillPackWindow();

static std::string DocumentationText[51] = { //								                              |
	"The ID of the text that will be used for the skill. This is generally 1 less than the skill ID. The Skill Text ID controls both the name and description.",
	"Register ID",
	"The skill's internal ID. Skill Editor uses this parameter to determine which skill to overwrite in memory. (If set to 32, it will overwrite skill #32 in memory)",
	"The skill's rarity. Represented in-game by a star rating in the arsenal editor.",
	"Determines what sound file will be used (?)\nNeeds more research / documentation.",
	"Determines what type the skill is, directly correlated to the skill's color. The capsule type also determines the skill profile, which changes how other parameters are read.\n\n0 = Aura\n1 = Attack\n2 = Defense\n3 = Erase\n4 = Environmental\n5 = Status\n6 = Special",
	"The skill's school. Values higher than 5 will cut off the skill info panel, or display garbage data.\n\n0 = Aura\n1 = Psycho\n2 = Optical\n3 = Nature\n4 = Ki\n5 = Faith",
	"This ID selects which animation \"profile\" or \"prefab\" will be used. This profile determines which skeletal animation (how the character moves) and shader animation (particle effects used when firing) are used. It also determines how many projectiles are fired in non-meelee attacks.\n\nThe Ground animation profile is used when using the skill on the ground, and the Air profile is\nused when using it in the air.",
	"I don't really understand what this does. Needs documentation.",
	"I don't really understand what this does. Needs documentation.",
	"I don't really understand what this does. Needs documentation.",
	"I don't really understand what this does. Needs documentation.",
	"The sound effect to be played after the skill hits *(?)* Needs more documentation.",
	"The sound effect ID to be played when the skill is winding up / charging.",
	"The sound effect ID to be played when the skill collides with something.",
	"The amount of Aura the skill will cost to use.",
	"Additional effects applied to the cost.\n\n0 = None\n1 = Reset Aura\n2 = Require Max Aura",
	"This value is added to the Aura Cost. Why not just increase the base Aura Cost instead? We don't know.",
	"Determines how much health to take from the user when the skill is used.",
	"Determines how many times the skill may be used before it's deleted / removed from your hand. Set this to 0 for infinite uses.",
	"An effect to be applied to the user. Undocumented, needs more research.",
	"Applies restrictions to the skill after use *(check)*. Needs more documentation / detail.\n\n0 = None\n1 = Can't use skill\n2 = Cut Audio Short\n3 = Cickable with error sound, can't use skill",
	"This parameter specifies special requirements that must be met in order to cast the skill. This only determines what type of requirement it will be, the next parameter sets the amount to be checked for (e.g. to require at least 15 health, this is set to 1 and the next parameter is set to 15)\n\n0 = None\n1 = Health\n5 = Number of skills left in your arsenal\n7 = Aura (Add more detail here)\n9 = Aura Level (Add more detail here)",
	"The required amount of the type specified in the previous box. If the required amount isn't met, the player can't use the skill.",
	"Determines where the skill can be used. In the provided editor, this is presented as a simple slider instead of a number input, since there are only 3 possible values.\n\n0 = Ground Only\n1 = Air Only\n2 = Anywhere",
	"I don't understand this parameter yet, the information and parameter name are from Nuion's\n[Attack Skill template spreadsheet](https://docs.google.com/spreadsheets/d/1zGqdi0Oeq14YHuMItYi2Qwhj4RhWZxho4hT7MLqRKCg).\n\n0 = Normal\n1 = Retainable\n2 = Lock Skill (orb)",
	"Determines the status type to be applied to the target when the skill hits. This entry has some extra details from in-game testing.\n\n0 = None\n1 = Aura Drain\n2 = Aura Level Decrease\n3 = Aura Drain\n4 = Aura Level Decrease\n5 = Explode (made my skill an enviromental, used \"0C 01\" on Status Enabler)\n6 = Paralysis (made my skill repeat the previous used one used \"0C 01\" on Status Enabler)\n7 = Frozen (made my skill crash the game used \"0C 01\" on Status Enabler)\n8 = Poison\n9 = Death\n10 = Freeze Same Button\n11 = Absorb Aura",
	"I don't understand this parameter yet, the information and parameter name are from Nuion's\n[Attack Skill template spreadsheet](https://docs.google.com/spreadsheets/d/1zGqdi0Oeq14YHuMItYi2Qwhj4RhWZxho4hT7MLqRKCg).\n\n0 = Normal\n1 = X Health Left to use\n5 = X Cards Left to use\n7 = Need Max Aura to use\n9 = Need X Aura Level",
	"I don't understand this parameter yet, the information and parameter name are from Nuion's\n[Attack Skill template spreadsheet](https://docs.google.com/spreadsheets/d/1zGqdi0Oeq14YHuMItYi2Qwhj4RhWZxho4hT7MLqRKCg).\n\n0 = Normal\n21 = Damage based on destructible\n28 = Random Damage\n24 = Dmg of unassigned buttons",
	"The amount of damage the skill deals when it hits an opponent.",
	"This parameter needs more research. Usually this controls effect duration, but apparently under specific circumstances it will increase the attack damage on every consecutive hit.\n\n0 = Infinite duration (use this if your skill doesnt have a duration)\n1 = ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
};

static std::string DocumentationLabels[51] = { //								    |
	"Skill Text ID",
	"Register ID",
	"Skill ID",
	"Rarity",
	"Sound File ID",
	"Capsule Type",
	"School ID",
	"Animation Profile",
	"Multi Press 1",
	"Multi Press 2",
	"Double Skills 1",
	"Double Skills 2",
	"After Hit SFX",
	"Start Up SFX",
	"Collision SFX",
	"Aura Cost",
	"Cost Effect",
	"Additional Aura Cost",
	"Health Penalty",
	"# of Uses",
	"Self Effect",
	"Button Restrictions",
	"Requirement Type",
	"Requirement Amount",
	"Ground/Air/Both",
	"Skill Button Effect",
	"Status ID",
	"Restriction",
	"Strength Effect",
	"Damage",
	"Duration / Misc. Effects",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
};
